# Generated by Django 4.0.3 on 2022-03-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='product',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Отображать в каталоге'),
        ),
    ]
