# Generated by Django 4.0.3 on 2022-03-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_category_description_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=128, verbose_name='Номер телефона для связи')),
                ('email', models.CharField(max_length=128, verbose_name='Email для связи')),
                ('address', models.CharField(max_length=128, verbose_name='Адрес')),
                ('work_time', models.CharField(max_length=128, verbose_name='Время работы')),
            ],
            options={
                'verbose_name': 'Настройки',
                'verbose_name_plural': 'Настройки',
            },
        ),
    ]
