# Generated by Django 4.0.3 on 2022-03-22 17:25

import autoslug.fields
from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_catalogsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, upload_to='products', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', verbose_name='Название для ulr'),
        ),
    ]
